apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: tanvihalankar/config-server:latest
        ports:
        - containerPort: 8888
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: https://github.com/TanviHalankar/cms-config-repo.git