apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: tanvihalankar/eureka:latest
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
