apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: hrms
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: attendance-service




