apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
      containers:
      - name: payroll
        image: tanvihalankar/payroll:latest
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/payroll_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
